export const GOODS_LIST_SAVE = "GOODS_LIST_SAVE";
export const WAREHOUSE_ITEM_LIST_SAVE = "WAREHOUSE_ITEM_LIST_SAVE";
export const WAREHOUSE_ITEM_UPDATE = "WAREHOUSE_ITEM_UPDATE";
export const GOODS_LIST_RENDER_SAVE = "GOODS_LIST_RENDER_SAVE";
export const GOODS_UPDATE = "GOODS_UPDATE";