export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const CONFIRM_ORDER = "CONFIRM_ORDER";

export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const INITIALIZE_FAVORITES = "INITIALIZE_FAVORITES";

export const SAVE_EMAIL = "SAVE_EMAIL";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SAVE_USER_ID = "SAVE_USER_ID";
export const UPDATE_USER_LIKES = "UPDATE_USER_LIKES";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_CREDIT = "UPDATE_USER_CREDIT";
