export const PRODUCT_ITEM_LIST = [
	{
		id: "1",
		title: "Cà Phê Sữa Đá",
		price: 30000,
		description: "Cà phê sữa đá thơm ngon",
		imageSource: require("../assets/vietnam.png"),
		type: "COFFEE",
		isFavorite: false,
	},
	{
		id: "2",
		title: "Trà Đào",
		price: 35000,
		description: "Trà đào thơm ngon",
		imageSource: require("../assets/vietnam.png"),
		type: "TEA",
		isFavorite: false,
	},
	{
		id: "3",
		title: "Trà Sữa Trân Châu",
		price: 40000,
		description: "Trà sữa trân châu thơm ngon",
		imageSource: require("../assets/vietnam.png"),
		type: "MILKTEA",
		isFavorite: false,
	},
	{
		id: "4",
		title: "Cà Phê Đen",
		price: 25000,
		description: "Cà phê đen thơm ngon",
		imageSource: require("../assets/vietnam.png"),
		type: "COFFEE",
		isFavorite: false,
	},
	{
		id: "5",
		title: "Trà Lúa Mạch",
		price: 30000,
		description: "Trà lúa mạch thơm ngon",
		imageSource: require("../assets/vietnam.png"),
		type: "TEA",
		isFavorite: false,
	},
	{
		id: "6",
		title: "Trà Sữa Matcha",
		price: 45000,
		description: "Trà sữa matcha thơm ngon",
		imageSource: require("../assets/vietnam.png"),
		type: "MILKTEA",
		isFavorite: false,
	},
];
